server:
  port: 9871
  servlet:
    context-path: /im
spring:
  application:
    name: Libre-IM
  profiles:
    active: dev

mybatis-plus:
  global-config:
    banner: false

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/libre?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 504879189
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

libre:
  redisson:
    single:
      address: 127.0.0.1:6379

logging:
  level:
    com.libre.im: debug

---


