server:
  port: 9871
  servlet:
    context-path: /im
spring:
  application:
    name: Libre-IM
  profiles:
    active: dev

mybatis-plus:
  global-config:
    banner: false

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:3306/libre_im
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

libre:
  redisson:
    single:
      address: 127.0.0.1:6379

---


