server:
  port: 9871
  servlet:
    context-path: /im
spring:
  application:
    name: Libre-IM
  profiles:
    active: dev
  cache:
    type: redis
    redis:
      time-to-live: 1h

mybatis-plus:
  global-config:
    banner: false

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:3306/libre_im
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

libre:
  redisson:
    single:
      address: 127.0.0.1:6379
  security:
    jwt-token:
      secret: 669da4ca0fde3928856705c8746512daa9957b91b0bbe855790b561d9f08be80
  captcha:
    enabled: true
  swagger:
    authorization:
      enabled: true

logging:
  level:
    com.libre: debug
---


