// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/libre/im/core/proto/TextMessage.proto

package com.libre.im.core.proto;

public final class TextMessageProto {
  private TextMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.libre.im.core.proto.TextMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>uint32 connectType = 2;</code>
     * @return The connectType.
     */
    int getConnectType();

    /**
     * <code>uint32 messageBodyType = 3;</code>
     * @return The messageBodyType.
     */
    int getMessageBodyType();

    /**
     * <code>uint64 sendUserId = 4;</code>
     * @return The sendUserId.
     */
    long getSendUserId();

    /**
     * <code>uint32 status = 5;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>string body = 6;</code>
     * @return The body.
     */
    java.lang.String getBody();
    /**
     * <code>string body = 6;</code>
     * @return The bytes for body.
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>uint64 acceptUserId = 7;</code>
     * @return The acceptUserId.
     */
    long getAcceptUserId();

    /**
     * <code>uint64 acceptGroupId = 8;</code>
     * @return The acceptGroupId.
     */
    long getAcceptGroupId();

    /**
     * <code>string createTime = 9;</code>
     * @return The createTime.
     */
    java.lang.String getCreateTime();
    /**
     * <code>string createTime = 9;</code>
     * @return The bytes for createTime.
     */
    com.google.protobuf.ByteString
        getCreateTimeBytes();
  }
  /**
   * Protobuf type {@code com.libre.im.core.proto.TextMessage}
   */
  public static final class TextMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.libre.im.core.proto.TextMessage)
      TextMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextMessage.newBuilder() to construct.
    private TextMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextMessage() {
      body_ = "";
      createTime_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TextMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt64();
              break;
            }
            case 16: {

              connectType_ = input.readUInt32();
              break;
            }
            case 24: {

              messageBodyType_ = input.readUInt32();
              break;
            }
            case 32: {

              sendUserId_ = input.readUInt64();
              break;
            }
            case 40: {

              status_ = input.readUInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 56: {

              acceptUserId_ = input.readUInt64();
              break;
            }
            case 64: {

              acceptGroupId_ = input.readUInt64();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              createTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.libre.im.core.proto.TextMessageProto.internal_static_com_libre_im_core_proto_TextMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.libre.im.core.proto.TextMessageProto.internal_static_com_libre_im_core_proto_TextMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.libre.im.core.proto.TextMessageProto.TextMessage.class, com.libre.im.core.proto.TextMessageProto.TextMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int CONNECTTYPE_FIELD_NUMBER = 2;
    private int connectType_;
    /**
     * <code>uint32 connectType = 2;</code>
     * @return The connectType.
     */
    @java.lang.Override
    public int getConnectType() {
      return connectType_;
    }

    public static final int MESSAGEBODYTYPE_FIELD_NUMBER = 3;
    private int messageBodyType_;
    /**
     * <code>uint32 messageBodyType = 3;</code>
     * @return The messageBodyType.
     */
    @java.lang.Override
    public int getMessageBodyType() {
      return messageBodyType_;
    }

    public static final int SENDUSERID_FIELD_NUMBER = 4;
    private long sendUserId_;
    /**
     * <code>uint64 sendUserId = 4;</code>
     * @return The sendUserId.
     */
    @java.lang.Override
    public long getSendUserId() {
      return sendUserId_;
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private int status_;
    /**
     * <code>uint32 status = 5;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int BODY_FIELD_NUMBER = 6;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 6;</code>
     * @return The body.
     */
    @java.lang.Override
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 6;</code>
     * @return The bytes for body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCEPTUSERID_FIELD_NUMBER = 7;
    private long acceptUserId_;
    /**
     * <code>uint64 acceptUserId = 7;</code>
     * @return The acceptUserId.
     */
    @java.lang.Override
    public long getAcceptUserId() {
      return acceptUserId_;
    }

    public static final int ACCEPTGROUPID_FIELD_NUMBER = 8;
    private long acceptGroupId_;
    /**
     * <code>uint64 acceptGroupId = 8;</code>
     * @return The acceptGroupId.
     */
    @java.lang.Override
    public long getAcceptGroupId() {
      return acceptGroupId_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 9;
    private volatile java.lang.Object createTime_;
    /**
     * <code>string createTime = 9;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public java.lang.String getCreateTime() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      }
    }
    /**
     * <code>string createTime = 9;</code>
     * @return The bytes for createTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (connectType_ != 0) {
        output.writeUInt32(2, connectType_);
      }
      if (messageBodyType_ != 0) {
        output.writeUInt32(3, messageBodyType_);
      }
      if (sendUserId_ != 0L) {
        output.writeUInt64(4, sendUserId_);
      }
      if (status_ != 0) {
        output.writeUInt32(5, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, body_);
      }
      if (acceptUserId_ != 0L) {
        output.writeUInt64(7, acceptUserId_);
      }
      if (acceptGroupId_ != 0L) {
        output.writeUInt64(8, acceptGroupId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createTime_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, createTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (connectType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, connectType_);
      }
      if (messageBodyType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, messageBodyType_);
      }
      if (sendUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, sendUserId_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, body_);
      }
      if (acceptUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, acceptUserId_);
      }
      if (acceptGroupId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, acceptGroupId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createTime_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, createTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.libre.im.core.proto.TextMessageProto.TextMessage)) {
        return super.equals(obj);
      }
      com.libre.im.core.proto.TextMessageProto.TextMessage other = (com.libre.im.core.proto.TextMessageProto.TextMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (getConnectType()
          != other.getConnectType()) return false;
      if (getMessageBodyType()
          != other.getMessageBodyType()) return false;
      if (getSendUserId()
          != other.getSendUserId()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (getAcceptUserId()
          != other.getAcceptUserId()) return false;
      if (getAcceptGroupId()
          != other.getAcceptGroupId()) return false;
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CONNECTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getConnectType();
      hash = (37 * hash) + MESSAGEBODYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageBodyType();
      hash = (37 * hash) + SENDUSERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendUserId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + ACCEPTUSERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAcceptUserId());
      hash = (37 * hash) + ACCEPTGROUPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAcceptGroupId());
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.libre.im.core.proto.TextMessageProto.TextMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.libre.im.core.proto.TextMessageProto.TextMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.libre.im.core.proto.TextMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.libre.im.core.proto.TextMessage)
        com.libre.im.core.proto.TextMessageProto.TextMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.libre.im.core.proto.TextMessageProto.internal_static_com_libre_im_core_proto_TextMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.libre.im.core.proto.TextMessageProto.internal_static_com_libre_im_core_proto_TextMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.libre.im.core.proto.TextMessageProto.TextMessage.class, com.libre.im.core.proto.TextMessageProto.TextMessage.Builder.class);
      }

      // Construct using com.libre.im.core.proto.TextMessageProto.TextMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        connectType_ = 0;

        messageBodyType_ = 0;

        sendUserId_ = 0L;

        status_ = 0;

        body_ = "";

        acceptUserId_ = 0L;

        acceptGroupId_ = 0L;

        createTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.libre.im.core.proto.TextMessageProto.internal_static_com_libre_im_core_proto_TextMessage_descriptor;
      }

      @java.lang.Override
      public com.libre.im.core.proto.TextMessageProto.TextMessage getDefaultInstanceForType() {
        return com.libre.im.core.proto.TextMessageProto.TextMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.libre.im.core.proto.TextMessageProto.TextMessage build() {
        com.libre.im.core.proto.TextMessageProto.TextMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.libre.im.core.proto.TextMessageProto.TextMessage buildPartial() {
        com.libre.im.core.proto.TextMessageProto.TextMessage result = new com.libre.im.core.proto.TextMessageProto.TextMessage(this);
        result.id_ = id_;
        result.connectType_ = connectType_;
        result.messageBodyType_ = messageBodyType_;
        result.sendUserId_ = sendUserId_;
        result.status_ = status_;
        result.body_ = body_;
        result.acceptUserId_ = acceptUserId_;
        result.acceptGroupId_ = acceptGroupId_;
        result.createTime_ = createTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.libre.im.core.proto.TextMessageProto.TextMessage) {
          return mergeFrom((com.libre.im.core.proto.TextMessageProto.TextMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.libre.im.core.proto.TextMessageProto.TextMessage other) {
        if (other == com.libre.im.core.proto.TextMessageProto.TextMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getConnectType() != 0) {
          setConnectType(other.getConnectType());
        }
        if (other.getMessageBodyType() != 0) {
          setMessageBodyType(other.getMessageBodyType());
        }
        if (other.getSendUserId() != 0L) {
          setSendUserId(other.getSendUserId());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (other.getAcceptUserId() != 0L) {
          setAcceptUserId(other.getAcceptUserId());
        }
        if (other.getAcceptGroupId() != 0L) {
          setAcceptGroupId(other.getAcceptGroupId());
        }
        if (!other.getCreateTime().isEmpty()) {
          createTime_ = other.createTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.libre.im.core.proto.TextMessageProto.TextMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.libre.im.core.proto.TextMessageProto.TextMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>uint64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int connectType_ ;
      /**
       * <code>uint32 connectType = 2;</code>
       * @return The connectType.
       */
      @java.lang.Override
      public int getConnectType() {
        return connectType_;
      }
      /**
       * <code>uint32 connectType = 2;</code>
       * @param value The connectType to set.
       * @return This builder for chaining.
       */
      public Builder setConnectType(int value) {
        
        connectType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 connectType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectType() {
        
        connectType_ = 0;
        onChanged();
        return this;
      }

      private int messageBodyType_ ;
      /**
       * <code>uint32 messageBodyType = 3;</code>
       * @return The messageBodyType.
       */
      @java.lang.Override
      public int getMessageBodyType() {
        return messageBodyType_;
      }
      /**
       * <code>uint32 messageBodyType = 3;</code>
       * @param value The messageBodyType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBodyType(int value) {
        
        messageBodyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 messageBodyType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageBodyType() {
        
        messageBodyType_ = 0;
        onChanged();
        return this;
      }

      private long sendUserId_ ;
      /**
       * <code>uint64 sendUserId = 4;</code>
       * @return The sendUserId.
       */
      @java.lang.Override
      public long getSendUserId() {
        return sendUserId_;
      }
      /**
       * <code>uint64 sendUserId = 4;</code>
       * @param value The sendUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSendUserId(long value) {
        
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 sendUserId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendUserId() {
        
        sendUserId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>uint32 status = 5;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>uint32 status = 5;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 status = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 6;</code>
       * @return The body.
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 6;</code>
       * @return The bytes for body.
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 6;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 6;</code>
       * @param value The bytes for body to set.
       * @return This builder for chaining.
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private long acceptUserId_ ;
      /**
       * <code>uint64 acceptUserId = 7;</code>
       * @return The acceptUserId.
       */
      @java.lang.Override
      public long getAcceptUserId() {
        return acceptUserId_;
      }
      /**
       * <code>uint64 acceptUserId = 7;</code>
       * @param value The acceptUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptUserId(long value) {
        
        acceptUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 acceptUserId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAcceptUserId() {
        
        acceptUserId_ = 0L;
        onChanged();
        return this;
      }

      private long acceptGroupId_ ;
      /**
       * <code>uint64 acceptGroupId = 8;</code>
       * @return The acceptGroupId.
       */
      @java.lang.Override
      public long getAcceptGroupId() {
        return acceptGroupId_;
      }
      /**
       * <code>uint64 acceptGroupId = 8;</code>
       * @param value The acceptGroupId to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptGroupId(long value) {
        
        acceptGroupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 acceptGroupId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearAcceptGroupId() {
        
        acceptGroupId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object createTime_ = "";
      /**
       * <code>string createTime = 9;</code>
       * @return The createTime.
       */
      public java.lang.String getCreateTime() {
        java.lang.Object ref = createTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string createTime = 9;</code>
       * @return The bytes for createTime.
       */
      public com.google.protobuf.ByteString
          getCreateTimeBytes() {
        java.lang.Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string createTime = 9;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string createTime = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = getDefaultInstance().getCreateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string createTime = 9;</code>
       * @param value The bytes for createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.libre.im.core.proto.TextMessage)
    }

    // @@protoc_insertion_point(class_scope:com.libre.im.core.proto.TextMessage)
    private static final com.libre.im.core.proto.TextMessageProto.TextMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.libre.im.core.proto.TextMessageProto.TextMessage();
    }

    public static com.libre.im.core.proto.TextMessageProto.TextMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextMessage>
        PARSER = new com.google.protobuf.AbstractParser<TextMessage>() {
      @java.lang.Override
      public TextMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.libre.im.core.proto.TextMessageProto.TextMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_libre_im_core_proto_TextMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_libre_im_core_proto_TextMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)com/libre/im/core/proto/TextMessage.pr" +
      "oto\022\027com.libre.im.core.proto\"\272\001\n\013TextMes" +
      "sage\022\n\n\002id\030\001 \001(\004\022\023\n\013connectType\030\002 \001(\r\022\027\n" +
      "\017messageBodyType\030\003 \001(\r\022\022\n\nsendUserId\030\004 \001" +
      "(\004\022\016\n\006status\030\005 \001(\r\022\014\n\004body\030\006 \001(\t\022\024\n\014acce" +
      "ptUserId\030\007 \001(\004\022\025\n\racceptGroupId\030\010 \001(\004\022\022\n" +
      "\ncreateTime\030\t \001(\tB+\n\027com.libre.im.core.p" +
      "rotoB\020TextMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_libre_im_core_proto_TextMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_libre_im_core_proto_TextMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_libre_im_core_proto_TextMessage_descriptor,
        new java.lang.String[] { "Id", "ConnectType", "MessageBodyType", "SendUserId", "Status", "Body", "AcceptUserId", "AcceptGroupId", "CreateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
